# Copy common Windows fonts into public/fonts/ (run from project root).
$ErrorActionPreference = "Stop"
$src = "$env:WINDIR\Fonts"
$dst = Join-Path $PSScriptRoot "..\public\fonts"

Copy-Item "$src\consola.ttf"  "$dst\Consolas.ttf"
Copy-Item "$src\consolab.ttf" "$dst\Consolas-Bold.ttf"
Copy-Item "$src\cour.ttf"     "$dst\CourierNew.ttf"
Copy-Item "$src\courbd.ttf"   "$dst\CourierNew-Bold.ttf"
Copy-Item "$src\calibri.ttf"  "$dst\Calibri.ttf"
Copy-Item "$src\calibrib.ttf" "$dst\Calibri-Bold.ttf"
Copy-Item "$src\arial.ttf"    "$dst\Arial.ttf"
Copy-Item "$src\arialbd.ttf"  "$dst\Arial-Bold.ttf"
Copy-Item "$src\georgia.ttf"  "$dst\Georgia.ttf"
Copy-Item "$src\georgiab.ttf" "$dst\Georgia-Bold.ttf"
Copy-Item "$src\times.ttf"    "$dst\TimesNewRoman.ttf"
Copy-Item "$src\timesbd.ttf"  "$dst\TimesNewRoman-Bold.ttf"
Copy-Item "$src\verdana.ttf"  "$dst\Verdana.ttf"
Copy-Item "$src\verdanab.ttf" "$dst\Verdana-Bold.ttf"
Copy-Item "$src\segoeui.ttf"  "$dst\SegoeUI.ttf"
Copy-Item "$src\segoeuib.ttf" "$dst\SegoeUI-Bold.ttf"

Write-Host "Fonts copied to $dst"
Write-Host "Run: npm run verify-fonts"
